### ISSUE TITLE
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

### ISSUE THREAD

**Issue by VincentXWD** [loli/medpy#69] opened 2018-03-02 05:56 UTC
https://github.com/loli/medpy/blob/7e9e332faf3815b8a99e985a412c0234789739cd/medpy/metric/binary.py#L1169

when i used these two pieces of codes:
evaluate.py : https://paste.ubuntu.com/p/87yBYMhctC/
surface.py: https://paste.ubuntu.com/p/Q72rb2PH7j/

 i got an error:
`
Traceback (most recent call last):
  File "evaluate.py", line 79, in <module>
    outpath='117_baseline.csv')
  File "evaluate.py", line 42, in evaluate
    loaded_label.header.get_zooms()[:3])
  File "evaluate.py", line 26, in get_scores
    volscores['msd'] = metric.hd(label, pred, voxelspacing=vxlspacing)
  File "/xwd/envs/python27/lib/python2.7/site-packages/medpy/metric/binary.py", line 348, in hd
    hd1 = __surface_distances(result, reference, voxelspacing, connectivity).max()
  File "/xwd/envs/python27/lib/python2.7/site-packages/medpy/metric/binary.py", line 1169, in __surface_distances
    result_border = result - binary_erosion(result, structure=footprint, iterations=1)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
`

and i noticed they used medpy. the bug is occured in these two lines:
`
result_border = result - binary_erosion(result, structure=footprint, iterations=1)
reference_border = reference - binary_erosion(reference, structure=footprint, iterations=1)
`
i changed these two lines to:
`
result_border = result ^ binary_erosion(result, structure=footprint, iterations=1)
reference_border = reference ^ binary_erosion(reference, structure=footprint, iterations=1)
`
and it works. so please tell me why. thanks.

**Comment by loli** [comment] 2018-03-04 14:25
Thanks for pointing this out.

Numpy seems to have treated booleans differently than native Python, leading to unexpected behaviour. I assume that's the reason they included the depreciation version in newer numpy versions.

Python: 
```
>>> False - True
-1
```

Numpy:
```
>>> np.False_ - np.True_
np.True_
```
We'll change it for the next release.

**Comment by loli** [comment] 2018-03-04 14:26
Resolved with #70

**Closed by loli** 2018-03-04 14:26 UTC
Labels: bug, enhancement
