### ISSUE TITLE
There is a bug in assd solution

### ISSUE THREAD

**Issue by Miraclerice** [loli/medpy#133] opened 2024-07-23 05:23 UTC
https://github.com/loli/medpy/blob/91d31a7e2707c70ff3bccff0746d2dde56daa6fe/medpy/metric/binary.py#L472

There is a bug in assd solution. The one-dimensional array dimensions of the predicted label and the surface distance calculated by gt are inconsistent. Should we use `assd=numpy.mean(numpy.concatenate(__surface_distances(result, reference, voxelspacing, connectivity), __surface_distances(reference, result, voxelspacing, connectivity), ) ) here? If I understand correctly, @loli

**Comment by Miraclerice** [comment] 2024-07-23 05:26
Sorry for the duplicate question, this is exactly what [issue131](https://github.com/loli/medpy/issues/131#issue-2226562866) asked

**Comment by loli** [comment] 2024-07-23 10:52
Np, thanks for reporting! Addressing now :)

**Comment by loli** [comment] 2024-07-23 10:52
Duplicate of #131

**Closed by loli** 2024-07-23 10:52 UTC
