### ISSUE TITLE
Error importing medpy.io's load

### ISSUE THREAD

**Issue by plooney** [loli/medpy#6] opened 2014-10-06 08:29 UTC
I have installed using pip3

> > > from medpy.io import load
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python3.4/dist-packages/medpy/io/**init**.py", line 59, in <module>
> > >     from .load import load
> > >   File "/usr/local/lib/python3.4/dist-packages/medpy/io/load.py", line 28, in <module>
> > >     from . import header
> > >   File "/usr/local/lib/python3.4/dist-packages/medpy/io/header.py", line 27, in <module>
> > >     from ..core import Logger
> > >   File "/usr/local/lib/python3.4/dist-packages/medpy/core/**init**.py", line 55, in <module>
> > >     from .logger import Logger
> > >   File "/usr/local/lib/python3.4/dist-packages/medpy/core/logger.py", line 94
> > >     raise RuntimeError, 'Only one instance of Logger is allowed!'

**Comment by MMRohe** [comment] 2016-01-10 21:44
Hello, I have exactly the same problem with medpy :
medpy.core.exceptions.ImageLoadingError: Failes to load image /user/mrohe/home/Data/Challange_Kaggle/Sax_mha_new/10/image_0.mha as Itk/Vtk MetaImage (.mhd, .mha/.raw). Reason signaled by third-party module: 'LazyITKModule' object has no attribute 'AnalyzeImageIO'

The problem is that the said module "AnalyzeImageIO" is deprecated under ITKv4 (which has already been running for quite a long time" so I don't really udnerstand how is it that medpy still needs it (http://www.itk.org/Doxygen42/html/classitk_1_1AnalyzeImageIO.html) ? Does it mean that I need to install ITKv3 to get medpy working with python?

Am I missing something here ?

**Comment by loli** [comment] 2016-01-11 13:21
Dear MMRohe,

thank you for reporting this and attaching your CMake config. As far as I can see, everything seems to be in order. MedPy has actually been testen with ITK 4.7 (http://pythonhosted.org/MedPy/installation/itkwrapper4.7.html), so I can't find the error immediately. You even have ITKV3_COMPATIBILITY=ON set, hence the AnalyzeImageIO should be available.

Today I am not a machine with ITK. I will look into the issue tomorrow and come back to you.

To tell the truth, keeping up with the changes in ITK and the very buggy behaviour of its Python Wrapper is very tedious and I often miss recent changes. I tend to use Convert3D (http://sourceforge.net/p/c3d/git/ci/master/tree/doc/c3d.md) to convert all images to NIfTI format and work with them, which improves stability and avoids loading the very large itk python module.

Best,
loli

**Comment by MMRohe** [comment] 2016-01-11 13:49
Hello loli,

thanks for your answer. I also use Nifti format and using it to make it 
work with Python could be a solution but with the data I am working on 
at the moment it would not be very convenient.

Indeed, the problem is quite weird. One think I could think of is that 
either the medpy version is outdated or the version of ITK that medPy is 
linked to is not the correct one (because I have several ITK versions on 
my computer) but I have double checked the link and the other ITK do not 
have the python wrapper built in anyway. Do you know if there is command 
inside python that could show exactly which version of the module it is 
using (I tried print medpy.__version__ or print itk.__version__ but 
these attributes dont exist).

Anyway, thanks a lot for your help, if you manage to get a solution or 
have any idea don't hesitate to contact me :)

Best,

Marc-Michel

**Comment by loli** [comment] 2016-01-13 14:16
The ITK wrappers are fragile things. Trying

    import inspect
    import itk
    inspect.getfile(itk)

tells me that it is an build-in module, which we know to be false. Well, nothing to be done about it. I could simply look at my PYTHONPATH to figure out, which one I am using.

Currently, I am still compiling ITK 4.7, I will come back to you later. It might take till next week, I fear :/

Best,
loli

**Comment by loli** [comment] 2016-01-13 15:08
Fixed with the newest commit to
https://github.com/loli/medpy/

Enjoy!
loli

**Comment by MMRohe** [comment] 2016-02-10 13:26
thx for your answer ! (and sorry I did not reply back earlier, had some 
problem with my comp so could not try it)

so it seems the update has fixed the previous issue but not I get the 
following message. It seems weird that it calls the load_nibabel 
function for a .mha image ?

ImageLoadingError                          Traceback (most recent call last)
<ipython-input-18-b6be7367b947>  in<module>() 20 pathImage='image.mha'21 ---> 22image_data, image_header = 
load(pathImage)23 #print 
image_data.shape()/medpy-master/medpy/io/load.py in load(image) 199 
logger.debug('Module {} signaled error: {}.'.format(loader, e))200 --> 
201raise err202 203 def __load_nibabel(image):ImageLoadingError: Failes 
to load image image.mha as Itk/Vtk MetaImage (.mhd, .mha/.raw). Reason 
signaled by third-party module: 'module' object has no attribute 'swig'

**Comment by loli** [comment] 2016-02-18 14:12
Mhh... my version is loading MHA images just fine. Could you attached a zipped version of your image for me for testing?

The __load_nibabel error results from the way MedPy loads images: First, it tries to find the best module depending on the image type. If that loader fails, it tries all available ones on a brute-force basis and returns the error of the last one tested.

**Comment by raghuramdr** [comment] 2016-04-29 16:43
I don't know if this issue is still being tracked, but I am also having similar problems. When I try to load .mha files, I get a bunch of warnings, followed by the error: 
     **raise err
medpy.core.exceptions.ImageLoadingError: Failes to load image Registered-1808820224_Classification.mha as Itk/Vtk MetaImage (.mhd, .mha/.raw). Reason signaled by third-party module: 'LazyITKModule' object has no attribute 'AnalyzeImageIO'
**

I set the ITK V3_COMPATIBILITY flag = ON during make. I am using ITK 4.9.

**Comment by loli** [comment] 2016-05-02 10:44
Did you install the PYPI 2.2 or the GitHub develoment version?

**Comment by sajjo79** [comment] 2017-05-16 03:09
Hi loli,
I am getting same error as of raghuramdr. How can i correct it . 

Best

**Comment by rcasero** [comment] 2017-06-29 13:45
Same problem as @plooney.

Conda virtual environment with python 3.6.1, numpy 1.12.1 and scipy 0.19.0.

I install medpy with 

    $ pip install medpy
    Collecting medpy
    Requirement already satisfied: numpy>=1.6.1 in /home/rcasero/.conda/envs/cytometer/lib/python3.6/site-packages (from medpy)
    Requirement already satisfied: scipy>=0.9.0 in /home/rcasero/.conda/envs/cytometer/lib/python3.6/site-packages (from medpy)
    Installing collected packages: medpy
    Successfully installed medpy-0.2.2

Then, importing load() fails

    $ python -c 'from medpy.io import load'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/rcasero/.conda/envs/cytometer/lib/python3.6/site-packages/medpy/io/__init__.py", line 59, in <module>
        from .load import load
      File "/home/rcasero/.conda/envs/cytometer/lib/python3.6/site-packages/medpy/io/load.py", line 28, in <module>
        from . import header
      File "/home/rcasero/.conda/envs/cytometer/lib/python3.6/site-packages/medpy/io/header.py", line 27, in <module>
        from ..core import Logger
      File "/home/rcasero/.conda/envs/cytometer/lib/python3.6/site-packages/medpy/core/__init__.py", line 55, in <module>
        from .logger import Logger
      File "/home/rcasero/.conda/envs/cytometer/lib/python3.6/site-packages/medpy/core/logger.py", line 94
        raise RuntimeError, 'Only one instance of Logger is allowed!'
                          ^
    SyntaxError: invalid syntax

**Comment by kvrd18** [comment] 2017-06-30 08:55
Same error as @rcasero

**Comment by rcasero** [comment] 2017-06-30 09:28
@loli , details on how to reproduce the error

1. Install [conda](https://conda.io/docs/intro.html)
   1. Download the [Miniconda bash installer](https://conda.io/miniconda.html) (e.g. for linux 64-bit, `Miniconda2-latest-Linux-x86_64.sh`).
   1. Make the script executable and run it as root

            cd ~/Downloads
            chmod u+x Miniconda2-latest-Linux-x86_64.sh
            sudo ./Miniconda2-latest-Linux-x86_64.sh
   1. When it asks for the install destination, select `/opt/miniconda2`, rather than the default `/home/rcasero/miniconda2`.
   1. "Do you wish the installer to prepend the Miniconda2 install location to PATH in your /home/rcasero/.bashrc ? [yes|no]". Select yes.

1. Create a conda environment for the test (python 3.6 at the time of this writing)

        conda create --name test python=3
1. Activate the conda environment 

        source activate test
1. Install medpy

        pip install medpy
1. test medpy

        python -c 'from medpy.io import load'
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/home/rcasero/.conda/envs/test/lib/python3.6/site-packages/medpy/io/__init__.py", line 59, in <module>
            from .load import load
          File "/home/rcasero/.conda/envs/test/lib/python3.6/site-packages/medpy/io/load.py", line 28, in <module>
            from . import header
          File "/home/rcasero/.conda/envs/test/lib/python3.6/site-packages/medpy/io/header.py", line 27, in <module>
            from ..core import Logger
          File "/home/rcasero/.conda/envs/test/lib/python3.6/site-packages/medpy/core/__init__.py", line 55, in <module>
            from .logger import Logger
          File "/home/rcasero/.conda/envs/test/lib/python3.6/site-packages/medpy/core/logger.py", line 94
            raise RuntimeError, 'Only one instance of Logger is allowed!'
                              ^
        SyntaxError: invalid syntax

**Comment by loli** [comment] 2017-07-03 09:46
This thread addresses two separate problems which are both solved.

**Problem 1** `raise RuntimeError, 'Only one instance of Logger is allowed!'`
If you are encountering this problem, you are using Python 3. Officially, MedPy only supports Python 2. But, thanks for an effort from @mamrehn, the current master branch might just be Python 3 compatible. I.e., get the newest MedPy version from https://github.com/loli/medpy. (@rcasero and @kvrd18)

**Problem 2** `Reason signaled by third-party module: 'LazyITKModule' object has no attribute 'AnalyzeImageIO'`
See Issue #15. Solved in the master current master branch. I.e., get the newest MedPy version from https://github.com/loli/medpy. (@raghuramdr and @sajjo79)

**Closed by loli** 2017-07-03 09:46 UTC
Labels: python3 issue
